"""
Curated seed data — well-known Canadian scholarships across all study levels.
These are hardcoded so the database always has quality entries regardless of
whether the web scrapers succeed on a given run.
"""
from scraper.base import BaseScraper, ScholarshipRecord

SEED_SCHOLARSHIPS = [

    # ─── HIGH SCHOOL ────────────────────────────────────────────────────────

    ScholarshipRecord(
        name="Loran Award",
        provider="Loran Scholars Foundation",
        description="One of Canada's most prestigious undergraduate scholarships, awarded to students who demonstrate strength of character, service to community, and promise of leadership.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering first year of undergraduate study",
            "Strong community involvement and leadership",
            "Minimum 85% average (varies by school)",
        ],
        url="https://loranscholar.ca/becoming-a-scholar/",
        source_domain="loranscholar.ca",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$100,000 over 4 years + mentorship",
        deadline_display="Early November (check website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Schulich Leader Scholarships",
        provider="Schulich Foundation",
        description="Canada's most valuable STEM scholarship at 20 Canadian universities. Awarded to entrepreneurial-minded students entering a STEM undergraduate program.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering first year of an eligible STEM program",
            "Demonstrated entrepreneurial spirit and leadership",
            "Financial need may be considered",
        ],
        url="https://schulichleaders.com",
        source_domain="schulichleaders.com",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$100,000 (STEM) or $80,000 (other)",
        deadline_display="Nominated by high school — check with your school counsellor",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="TD Scholarship for Community Leadership",
        provider="TD Bank Group",
        description="Awarded to students who have made a significant difference in their communities through volunteer and leadership activities.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering post-secondary education",
            "Demonstrated outstanding community leadership",
            "Financial need is considered",
        ],
        url="https://www.td.com/ca/en/about-td/community/scholarships/",
        source_domain="td.com",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $70,000 over 4 years",
        deadline_display="February (check TD website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Terry Fox Humanitarian Award",
        provider="Terry Fox Humanitarian Award Program",
        description="Awarded to Canadians who exemplify Terry Fox's humanitarian spirit by pursuing a post-secondary education while making an extraordinary contribution to the quality of life of Canadians through volunteer and humanitarian work.",
        eligibility_criteria=[
            "Canadian citizen or landed immigrant",
            "Entering or enrolled in Canadian post-secondary institution",
            "Demonstrated humanitarian and volunteer work",
            "Well-rounded with athletic involvement preferred",
        ],
        url="https://terryfox.org/award/",
        source_domain="terryfox.org",
        levels=["high_school", "undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $28,000/year",
        deadline_display="February 1",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Mackenzie King Open Scholarship",
        provider="Mackenzie King Scholarship Trust",
        description="Open to graduates of any Canadian university who pursue graduate study in Canada or elsewhere in any discipline.",
        eligibility_criteria=[
            "Graduate of a Canadian university",
            "Planning to pursue graduate studies",
            "Open to all disciplines",
            "Must be a Canadian citizen",
        ],
        url="https://www.mkingscholarships.ca",
        source_domain="mkingscholarships.ca",
        levels=["high_school", "undergraduate"],
        categories=["citizen"],
        amount="$11,000",
        deadline_display="February 1",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Canada Post Community Foundation Scholarships",
        provider="Canada Post Community Foundation",
        description="Supports young Canadians in their pursuit of post-secondary education. Awards are given to students who demonstrate academic excellence, community involvement, and financial need.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Age 24 or younger at time of application",
            "Enrolled or planning to enroll in post-secondary education",
            "Demonstrated financial need and community involvement",
        ],
        url="https://www.canadapostcommunityfoundation.ca/scholarships/",
        source_domain="canadapostcommunityfoundation.ca",
        levels=["high_school", "diploma", "undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 – $4,000",
        deadline_display="February (check website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Horatio Alger Canadian Scholarships",
        provider="Horatio Alger Association of Canada",
        description="Awarded to Canadians who have demonstrated integrity and perseverance in overcoming personal adversity and who aspire to pursue post-secondary education.",
        eligibility_criteria=[
            "Canadian citizen",
            "Enrolled in Grade 11 or 12 (or CEGEP equivalent)",
            "Demonstrated financial need",
            "Have faced and overcome adversity",
            "Minimum 65% average",
        ],
        url="https://www.horatioalger.ca/en/scholarships/",
        source_domain="horatioalger.ca",
        levels=["high_school"],
        categories=["citizen"],
        amount="Up to $7,500",
        deadline_display="October 25",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="RBC Future Launch Scholarship",
        provider="RBC (Royal Bank of Canada)",
        description="Supports young Canadians as they prepare for the future of work, with a focus on those facing barriers to employment.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Age 15–29",
            "Enrolled in or planning to attend post-secondary education",
            "Demonstrated financial need or barrier to education",
        ],
        url="https://www.rbc.com/community-social-impact/rbc-future-launch/scholarships.html",
        source_domain="rbc.com",
        levels=["high_school", "diploma", "undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="Varies by program",
        deadline_display="Check RBC website for current programs",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Indspire Building Brighter Futures Bursaries & Scholarships",
        provider="Indspire",
        description="Canada's largest Indigenous-led registered charity investing in Indigenous education. Provides scholarships to First Nations, Métis, and Inuit students.",
        eligibility_criteria=[
            "First Nations, Métis, or Inuit student",
            "Canadian citizen or permanent resident",
            "Enrolled in or applying to a Canadian post-secondary institution",
            "Demonstrated financial need",
        ],
        url="https://indspire.ca/for-students/bursaries-scholarships/",
        source_domain="indspire.ca",
        levels=["high_school", "diploma", "undergraduate", "masters"],
        categories=["citizen", "permanent_resident"],
        amount="$3,000 – $20,000+",
        deadline_display="March 1 and September 1 (two intakes)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Harry Jerome Scholarships",
        provider="Black Business and Professional Association (BBPA)",
        description="Awarded to Black-Canadian students who demonstrate academic achievement, community service, and leadership potential.",
        eligibility_criteria=[
            "Self-identified Black-Canadian student",
            "Canadian citizen or permanent resident",
            "Enrolled in a Canadian post-secondary institution",
            "Demonstrated community involvement",
        ],
        url="https://www.bbpa.org/harry-jerome-scholarships/",
        source_domain="bbpa.org",
        levels=["high_school", "undergraduate", "masters"],
        categories=["citizen", "permanent_resident"],
        amount="$2,500 – $5,000",
        deadline_display="May 31",
        is_ra_ta=False,
    ),

    # ─── DIPLOMA ────────────────────────────────────────────────────────────

    ScholarshipRecord(
        name="Apprenticeship Incentive Grant (AIG)",
        provider="Government of Canada — Employment and Social Development",
        description="A taxable cash grant for registered apprentices who have completed their first or second year of a Red Seal trade apprenticeship program.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or protected person",
            "Registered apprentice in a Red Seal trade",
            "Completed first or second year of apprenticeship",
        ],
        url="https://www.canada.ca/en/employment-social-development/services/apprentices/grants.html",
        source_domain="canada.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 per year (first and second year)",
        deadline_display="Within 12 months of completing your level",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Apprenticeship Completion Grant (ACG)",
        provider="Government of Canada — Employment and Social Development",
        description="A taxable cash grant for apprentices who complete their apprenticeship and receive their journeyperson certification in a designated Red Seal trade.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or protected person",
            "Completed apprenticeship in a Red Seal trade",
            "Received journeyperson certification",
        ],
        url="https://www.canada.ca/en/employment-social-development/services/apprentices/grants.html",
        source_domain="canada.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$2,000",
        deadline_display="Within 12 months of receiving certification",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Women in Skilled Trades Scholarship — Ontario",
        provider="Ontario Ministry of Labour, Immigration, Training and Skills Development",
        description="Supports women enrolled in apprenticeship programs or pre-apprenticeship training in skilled trades in Ontario.",
        eligibility_criteria=[
            "Self-identified woman",
            "Ontario resident",
            "Registered in an apprenticeship program or pre-apprenticeship training",
            "Enrolled in an in-school training component of a trade",
        ],
        url="https://www.ontario.ca/page/scholarships-women-skilled-trades-and-technology",
        source_domain="ontario.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$5,000",
        deadline_display="Check Ontario.ca for current intake",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="BC Trades & Technology Scholarship",
        provider="Government of British Columbia — StudentAid BC",
        description="Supports students in trades and technology programs at B.C. public post-secondary institutions.",
        eligibility_criteria=[
            "BC resident",
            "Enrolled in an eligible trades or technology program at a BC public institution",
            "Canadian citizen, permanent resident, or protected person",
            "Demonstrated financial need",
        ],
        url="https://studentaidbc.ca/explore/scholarships-and-grants",
        source_domain="studentaidbc.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $4,000",
        deadline_display="Check StudentAid BC website",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Alberta Apprenticeship & Industry Training Scholarships",
        provider="Government of Alberta — Apprenticeship and Industry Training",
        description="Scholarships for Alberta apprentices who demonstrate academic excellence and commitment to their trade.",
        eligibility_criteria=[
            "Alberta resident",
            "Registered apprentice in Alberta",
            "Completed at least one period of technical training",
            "Demonstrated academic achievement in training",
        ],
        url="https://www.alberta.ca/apprenticeship-scholarships",
        source_domain="alberta.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 – $5,000",
        deadline_display="June 30 (check Alberta.ca)",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="George Brown College Awards & Bursaries",
        provider="George Brown College",
        description="Various awards and bursaries available to George Brown College students based on academic merit, financial need, and program of study.",
        eligibility_criteria=[
            "Enrolled at George Brown College",
            "Varies by specific award — merit, need, or program-based",
        ],
        url="https://www.georgebrown.ca/current-students/services/financial-aid/awards-bursaries",
        source_domain="georgebrown.ca",
        levels=["diploma"],
        categories=["all"],
        amount="Varies ($500 – $5,000+)",
        deadline_display="September and January (check George Brown portal)",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Bow Valley College Scholarship Program",
        provider="Bow Valley College",
        description="Scholarships and bursaries for students enrolled at Bow Valley College in Calgary, including entrance awards and in-course awards.",
        eligibility_criteria=[
            "Enrolled at Bow Valley College",
            "Varies by award — merit or need-based",
            "Some awards open to international students",
        ],
        url="https://bowvalleycollege.ca/student-resources/financial-support/scholarships-and-bursaries",
        source_domain="bowvalleycollege.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $3,000",
        deadline_display="Varies by award (check BVC portal)",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="BCIT Excellence Awards",
        provider="British Columbia Institute of Technology (BCIT)",
        description="Various scholarships and awards for BCIT students across all programs, including trades, technology, business, and health sciences.",
        eligibility_criteria=[
            "Enrolled at BCIT",
            "Varies by award — some merit-based, some need-based",
            "Some open to international students",
        ],
        url="https://www.bcit.ca/financial-aid/awards/",
        source_domain="bcit.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $5,000",
        deadline_display="March 15 and September 30 (check BCIT portal)",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Conestoga College Scholarships & Awards",
        provider="Conestoga College",
        description="Merit-based and need-based scholarships for students enrolled in diploma and certificate programs at Conestoga College.",
        eligibility_criteria=[
            "Enrolled at Conestoga College",
            "Minimum GPA requirement varies by award",
            "Some awards open to international students",
        ],
        url="https://www.conestogac.on.ca/financial-aid/awards",
        source_domain="conestogac.on.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $2,500",
        deadline_display="Check Conestoga portal",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Seneca Polytechnic Awards",
        provider="Seneca Polytechnic",
        description="Wide range of awards for students in diploma, certificate, and degree programs at Seneca, including entrance scholarships and in-course awards.",
        eligibility_criteria=[
            "Enrolled at Seneca Polytechnic",
            "Academic achievement or demonstrated financial need",
            "Some awards open to international students",
        ],
        url="https://www.senecapolytechnic.ca/financial-aid/awards-scholarships.html",
        source_domain="senecapolytechnic.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $4,000",
        deadline_display="Check Seneca financial aid portal",
        province="Ontario",
        is_ra_ta=False,
    ),

    # ─── UNDERGRADUATE ───────────────────────────────────────────────────────

    ScholarshipRecord(
        name="Mitacs Globalink Research Internship",
        provider="Mitacs",
        description="A competitive initiative for international undergraduates from select countries to conduct 12-week research internships at Canadian universities under the supervision of Canadian faculty.",
        eligibility_criteria=[
            "International undergraduate student (not a Canadian citizen/PR)",
            "Completed at least 2 years of undergraduate study",
            "Strong academic record",
            "From one of Mitacs's partner countries",
        ],
        url="https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
        source_domain="mitacs.ca",
        levels=["undergraduate"],
        categories=["international"],
        amount="$6,000 CAD stipend for 12 weeks",
        deadline_display="September (check Mitacs website)",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="Ontario Trillium Scholarship (OTS)",
        provider="Government of Ontario",
        description="Attracts top international PhD students to study at Ontario universities. One of the most prestigious scholarships for international doctoral students.",
        eligibility_criteria=[
            "International student (not Canadian citizen or PR)",
            "Applying to or enrolled in a full-time PhD program at an Ontario university",
            "Exceptional academic achievement",
            "Nominated by the university",
        ],
        url="https://www.ontario.ca/page/ontario-trillium-scholarship",
        source_domain="ontario.ca",
        levels=["masters"],
        categories=["international"],
        amount="$40,000/year for up to 4 years",
        deadline_display="Nominated by university — check with your graduate department",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="3M National Student Fellowship",
        provider="3M Canada",
        description="Recognizes exceptional undergraduate students from across Canada who demonstrate academic excellence, community service, and leadership.",
        eligibility_criteria=[
            "Full-time undergraduate student at a Canadian university",
            "Canadian citizen or permanent resident",
            "Demonstrated academic excellence (minimum A average)",
            "Leadership and community involvement",
        ],
        url="https://www.3mcanada.ca/3M/en_CA/company-ca/all-3m-products/~/3M-National-Student-Fellowship/",
        source_domain="3mcanada.ca",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$5,000",
        deadline_display="March (check 3M Canada website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="McCall MacBain Scholarships at McGill",
        provider="McCall MacBain Foundation — McGill University",
        description="Full-funding scholarships for exceptional students pursuing master's or professional programs at McGill University, selected for their leadership potential and commitment to making a difference.",
        eligibility_criteria=[
            "Applying to a master's or professional program at McGill",
            "Open to Canadian citizens, permanent residents, and international students",
            "Demonstrated leadership, academic excellence, and community impact",
        ],
        url="https://www.mccallmacbainscholars.org",
        source_domain="mccallmacbainscholars.org",
        levels=["masters"],
        categories=["all"],
        amount="Full tuition + living stipend + mentorship",
        deadline_display="November (check McCall MacBain website)",
        university="McGill University",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Mitacs Accelerate",
        provider="Mitacs",
        description="Connects graduate students and postdocs with industry partners for research internships. Each 3-month unit provides a research award split between the student and faculty.",
        eligibility_criteria=[
            "Graduate student (master's or PhD) or postdoctoral fellow",
            "Enrolled at a Canadian university",
            "Canadian citizen, permanent resident, or international student",
            "Research project in partnership with an industry or non-profit partner",
        ],
        url="https://www.mitacs.ca/en/programs/accelerate",
        source_domain="mitacs.ca",
        levels=["masters"],
        categories=["all"],
        amount="$15,000 per 3-month unit (student receives $10,000)",
        deadline_display="Rolling applications — apply anytime",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="Trudeau Foundation Doctoral Scholarships",
        provider="Pierre Elliott Trudeau Foundation",
        description="Supports outstanding PhD candidates whose research focuses on one of the Foundation's four themes: human rights and dignity, responsible citizenship, Canada and the world, or people and their natural environment.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or international student studying in Canada",
            "Enrolled in a full-time PhD program at a Canadian university",
            "Research aligned with one of the four Foundation themes",
            "Demonstrated leadership and public engagement",
        ],
        url="https://www.trudeaufoundation.ca/programs/trudeau-scholarships",
        source_domain="trudeaufoundation.ca",
        levels=["masters"],
        categories=["all"],
        amount="$40,000/year for up to 3 years + travel allowance",
        deadline_display="Early December (check Trudeau Foundation website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Ontario Graduate Scholarship (OGS)",
        provider="Government of Ontario",
        description="Promotes excellence in graduate study at publicly-assisted universities in Ontario. Awards are merit-based and available across all disciplines.",
        eligibility_criteria=[
            "Ontario resident or enrolled at an Ontario university",
            "Enrolled in a graduate program (master's or PhD)",
            "Canadian citizen, permanent resident, or international student",
            "Strong academic record (A average or better)",
        ],
        url="https://osap.gov.on.ca/OSAPPortal/en/A-ZListofAid/PRDR019245.html",
        source_domain="ontario.ca",
        levels=["masters"],
        categories=["all"],
        amount="$15,000/year",
        deadline_display="Varies by university — typically January to March",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Alberta Graduate Excellence Scholarship (AGES)",
        provider="Government of Alberta",
        description="Recognizes and retains exceptional graduate students studying at Alberta post-secondary institutions.",
        eligibility_criteria=[
            "Enrolled in a graduate program at an Alberta university",
            "Canadian citizen, permanent resident, or international student",
            "Strong academic record",
            "Nominated by the university",
        ],
        url="https://www.alberta.ca/alberta-graduate-excellence-scholarship",
        source_domain="alberta.ca",
        levels=["masters"],
        categories=["all"],
        amount="$11,000/year",
        deadline_display="Nominated by university — check with graduate department",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Killam Doctoral Scholarships",
        provider="Canada Council for the Arts — Killam Program",
        description="Awarded to outstanding PhD students registered in Canadian universities that administer the Killam Program (UBC, Dalhousie, Alberta, Calgary, Western).",
        eligibility_criteria=[
            "Enrolled in a PhD program at UBC, Dalhousie, U of Alberta, U of Calgary, or Western",
            "Canadian citizen, permanent resident, or international student (varies by university)",
            "Nominated by the university",
            "Exceptional academic achievement and research potential",
        ],
        url="https://killam.ca/doctoral-scholarships/",
        source_domain="killam.ca",
        levels=["masters"],
        categories=["all"],
        amount="$30,000/year for 2 years",
        deadline_display="Nominated by university — check with graduate department",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Banting Postdoctoral Fellowships",
        provider="Government of Canada (NSERC / SSHRC / CIHR)",
        description="Provides funding to top-tier postdoctoral researchers, both nationally and internationally, who will positively contribute to Canada's economic, social, and research-based growth.",
        eligibility_criteria=[
            "Completed PhD within the last 3 years",
            "Canadian citizen, permanent resident, or international researcher",
            "Nominated by a Canadian university",
            "Exceptional research track record",
        ],
        url="https://banting.fellowships-bourses.gc.ca",
        source_domain="banting.fellowships-bourses.gc.ca",
        levels=["masters"],
        categories=["all"],
        amount="$70,000/year for 2 years",
        deadline_display="September (check Banting website)",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="UBC Graduate Support Initiative",
        provider="University of British Columbia",
        description="UBC guarantees a minimum funding package for PhD students across all faculties, combining fellowship, TA, and RA funding.",
        eligibility_criteria=[
            "Admitted to a full-time PhD program at UBC",
            "Canadian citizen, permanent resident, or international student",
            "Funding guaranteed for eligible PhD students",
        ],
        url="https://www.grad.ubc.ca/scholarships-awards-funding",
        source_domain="grad.ubc.ca",
        levels=["masters"],
        categories=["all"],
        amount="Varies — PhD funding packages typically $22,000+/year",
        deadline_display="Automatic upon admission — no separate application",
        university="University of British Columbia",
        province="British Columbia",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="University of Toronto Excellence Award (UTEA)",
        provider="University of Toronto",
        description="Entrance award for exceptional students admitted to undergraduate programs at the University of Toronto.",
        eligibility_criteria=[
            "Admitted to an undergraduate program at U of T",
            "Open to Canadian citizens, permanent residents, and international students",
            "Based on academic achievement at time of application",
            "No separate application required — automatic consideration",
        ],
        url="https://future.utoronto.ca/finances/awards/",
        source_domain="utoronto.ca",
        levels=["high_school"],
        categories=["all"],
        amount="$2,500 – $25,000",
        deadline_display="Automatic upon admission — no separate application",
        university="University of Toronto",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="UBC International Student Scholarships",
        provider="University of British Columbia",
        description="UBC offers a range of merit-based entrance scholarships for international students admitted to undergraduate programs.",
        eligibility_criteria=[
            "International student (non-Canadian)",
            "Admitted to a full-time undergraduate program at UBC",
            "Exceptional academic achievement",
            "No separate application — automatic consideration",
        ],
        url="https://students.ubc.ca/enrolment/finances/award-search/",
        source_domain="ubc.ca",
        levels=["high_school", "undergraduate"],
        categories=["international"],
        amount="$2,000 – $40,000",
        deadline_display="Automatic upon admission",
        university="University of British Columbia",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="McGill University Entrance Scholarships",
        provider="McGill University",
        description="Merit-based entrance scholarships automatically considered for all students admitted to McGill's undergraduate programs.",
        eligibility_criteria=[
            "Admitted to an undergraduate program at McGill",
            "Open to Canadian and international students",
            "Based on academic achievement",
            "No separate application required",
        ],
        url="https://www.mcgill.ca/studentaid/scholarships-bursaries/undergraduate/entrance",
        source_domain="mcgill.ca",
        levels=["high_school"],
        categories=["all"],
        amount="$3,000 – $12,000",
        deadline_display="Automatic upon admission",
        university="McGill University",
        province="Quebec",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="University of Waterloo International Master's Award of Excellence",
        provider="University of Waterloo",
        description="Awarded to exceptional international students who are admitted to a master's program at the University of Waterloo.",
        eligibility_criteria=[
            "International student (non-Canadian citizen/PR)",
            "Admitted to a full-time master's program at Waterloo",
            "Minimum 80% average in last two years of study",
            "Nominated by department",
        ],
        url="https://uwaterloo.ca/graduate-studies-postdoctoral-affairs/awards/university-waterloo-international-masters-award-excellence",
        source_domain="uwaterloo.ca",
        levels=["masters"],
        categories=["international"],
        amount="$5,000",
        deadline_display="Contact your department for deadline",
        university="University of Waterloo",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="FRQSC Doctoral Scholarships (Quebec)",
        provider="Fonds de recherche du Québec — Société et culture (FRQSC)",
        description="Supports doctoral students in the social sciences and humanities conducting research in Quebec universities.",
        eligibility_criteria=[
            "Enrolled in a doctoral program at a Quebec university",
            "Canadian citizen or permanent resident (or authorized to study in Quebec)",
            "Research in social sciences, humanities, or related fields",
            "Strong academic record",
        ],
        url="https://frq.gouv.qc.ca/en/program/doctoral-training-scholarships/",
        source_domain="frq.gouv.qc.ca",
        levels=["masters"],
        categories=["citizen", "permanent_resident"],
        amount="$20,000/year for up to 4 years",
        deadline_display="October (check FRQSC website)",
        province="Quebec",
        is_ra_ta=False,
    ),
]


class SeedScraper(BaseScraper):
    name = "seed"
    source_domain = "fundmydegree.com"

    def scrape(self) -> list[ScholarshipRecord]:
        import logging
        logger = logging.getLogger(__name__)
        logger.info(f"Loading {len(SEED_SCHOLARSHIPS)} curated seed scholarships")
        return SEED_SCHOLARSHIPS
