"""
Curated seed data — well-known Canadian scholarships across all study levels.

Level definitions used here:
  high_school  = scholarships for students CURRENTLY in Grades 9–12
  undergraduate = entrance scholarships (apply in Grade 12, money for university)
                  + awards for current undergraduate students
  diploma      = college / trades / certificate programs
  masters      = master's, PhD, and postdoctoral funding
"""
from scraper.base import BaseScraper, ScholarshipRecord

SEED_SCHOLARSHIPS = [

    # ─── HIGH SCHOOL (currently enrolled in Grades 9–12) ─────────────────────

    ScholarshipRecord(
        name="Royal Canadian Legion National Scholarships",
        provider="Royal Canadian Legion",
        description="The Legion offers scholarships to students currently in high school who are children, grandchildren, or legal wards of Legion members (or veterans). Awards are given through local, provincial, and national levels.",
        eligibility_criteria=[
            "Currently enrolled in high school (Grade 10–12)",
            "Child, grandchild, or legal ward of a Legion member or veteran",
            "Canadian citizen or permanent resident",
            "Academic achievement and demonstrated character",
        ],
        url="https://www.legion.ca/who-we-are/youth/scholarships",
        source_domain="legion.ca",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$500 – $5,000 (varies by level)",
        deadline_display="May (contact your local Legion branch)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Duke of Edinburgh's International Award — Canada",
        provider="Duke of Edinburgh's International Award Canada",
        description="A global youth development program for young people aged 14–24. Completing the Award at Bronze, Silver, or Gold level unlocks recognition and often tied bursary funding through participating schools and sponsors.",
        eligibility_criteria=[
            "Ages 14–24 (most participants complete during high school)",
            "Enrolled in a Canadian school or youth program",
            "Must complete all four sections: Skill, Physical, Volunteering, Adventurous Journey",
            "Gold Award participants may access additional bursary funding",
        ],
        url="https://www.dukeofed.org",
        source_domain="dukeofed.org",
        levels=["high_school"],
        categories=["all"],
        amount="Recognition + tied bursaries vary by sponsor ($500 – $2,000)",
        deadline_display="Rolling — enroll anytime through your school or DoE centre",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Canada-Wide Science Fair (CWSF) Awards",
        provider="Youth Science Canada",
        description="Canada's largest science fair competition for students in Grades 7–12. Top projects win cash prizes, scholarships, and international competition entries.",
        eligibility_criteria=[
            "Currently in Grades 7–12",
            "Must qualify through a regional science fair",
            "Open to all students in Canada",
            "Project must be original research in science, technology, engineering, or math",
        ],
        url="https://youthscience.ca/science-fairs/cwsf/",
        source_domain="youthscience.ca",
        levels=["high_school"],
        categories=["all"],
        amount="$500 – $15,000+ (varies by award category)",
        deadline_display="Regional fairs typically Feb–April; CWSF in May",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Rotary Youth Leadership Awards (RYLA)",
        provider="Rotary International — Canadian Clubs",
        description="Rotary clubs across Canada sponsor high school students to attend RYLA leadership camps. Some clubs also offer direct scholarships to high school students demonstrating leadership and community involvement.",
        eligibility_criteria=[
            "Currently in high school (Grades 10–12 typically)",
            "Demonstrated leadership potential and community service",
            "Sponsored by or connected to a local Rotary Club",
        ],
        url="https://www.rotary.org/en/our-programs/rotary-youth-leadership-awards",
        source_domain="rotary.org",
        levels=["high_school"],
        categories=["all"],
        amount="Varies by local club ($500 – $3,000)",
        deadline_display="Varies by local Rotary club — contact your nearest club",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Gauss / AMC Mathematics Competition Awards",
        provider="Centre for Education in Mathematics and Computing (CEMC) / MAA",
        description="Top performers in the Gauss (Grades 7–8), AMC 10/12 (Grades 10–12), and Canadian Senior Mathematics Contest receive cash prizes and scholarships.",
        eligibility_criteria=[
            "Currently enrolled in Grades 7–12",
            "Must achieve a qualifying score in the respective competition",
            "Open to all Canadian students",
        ],
        url="https://www.cemc.uwaterloo.ca/contests/contests.html",
        source_domain="cemc.uwaterloo.ca",
        levels=["high_school"],
        categories=["all"],
        amount="$100 – $2,000 (varies by competition and placement)",
        deadline_display="Contests held in November and February each year",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Manitoba Scholarship and Bursary Initiative — High School",
        provider="Government of Manitoba",
        description="Manitoba offers a range of bursaries and entrance awards for Grade 12 students, including the Manitoba Scholarship for high-achieving students currently completing high school.",
        eligibility_criteria=[
            "Manitoba resident in Grade 12",
            "Minimum 85% average",
            "Canadian citizen or permanent resident",
            "Automatic consideration based on Manitoba Grade 12 results",
        ],
        url="https://www.edu.gov.mb.ca/ael/pse/funding_mb/msbi.html",
        source_domain="gov.mb.ca",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$500 – $2,500",
        deadline_display="Awarded automatically based on Grade 12 results (June)",
        province="Manitoba",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Alberta Heritage Scholarship Fund — High School Awards",
        provider="Government of Alberta — Alberta Student Aid",
        description="Alberta offers multiple awards for Grade 12 students currently in high school, including the Alexander Rutherford Scholarship and the Queen Elizabeth II Scholarships.",
        eligibility_criteria=[
            "Alberta resident currently in Grade 10, 11, or 12",
            "Minimum 75%–80% average (varies by award)",
            "Canadian citizen or permanent resident",
            "Enrolled in an Alberta high school",
        ],
        url="https://studentaid.alberta.ca/scholarships-and-awards/alberta-scholarships/",
        source_domain="studentaid.alberta.ca",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$400 – $2,500 depending on award",
        deadline_display="Grades submitted to Alberta Student Aid — automatic consideration",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="BC Passport to Education",
        provider="Government of British Columbia",
        description="BC students in Grades 10–12 can earn scholarship credits through community service, leadership, and academic achievement, redeemable for post-secondary funding.",
        eligibility_criteria=[
            "Currently enrolled in Grades 10–12 in a BC school",
            "Participate in approved volunteer and leadership activities",
            "Attend a BC public or independent school",
        ],
        url="https://www2.gov.bc.ca/gov/content/education-training/k-12/support/scholarships",
        source_domain="gov.bc.ca",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $3,500 in redeemable credits",
        deadline_display="Credits accumulated throughout Grades 10–12",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Governor General's Academic Medal",
        provider="Office of the Secretary to the Governor General",
        description="Awarded to students with the highest academic standing at graduation from high school. The Bronze Medal is for secondary school graduates and is one of Canada's oldest and most prestigious academic distinctions.",
        eligibility_criteria=[
            "Graduating Grade 12 student (or equivalent)",
            "Highest academic average in graduating class",
            "Nominated by the school — no application required",
        ],
        url="https://www.gg.ca/en/honours/governor-generals-academic-medal",
        source_domain="gg.ca",
        levels=["high_school"],
        categories=["all"],
        amount="Prestigious recognition (no cash award — opens doors to other scholarships)",
        deadline_display="Awarded at graduation by your school",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Scotiabank Youth Scholarship Program",
        provider="Scotiabank",
        description="Scotiabank provides scholarships to high school students across Canada who demonstrate academic excellence, leadership, and community involvement through its community giving programs.",
        eligibility_criteria=[
            "Currently in high school",
            "Canadian citizen or permanent resident",
            "Demonstrated academic achievement and community involvement",
            "Check Scotiabank's current programs — offerings vary by region",
        ],
        url="https://www.scotiabank.com/ca/en/about/community-sustainability/community/scholarships.html",
        source_domain="scotiabank.com",
        levels=["high_school"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 – $5,000",
        deadline_display="Check Scotiabank website for current intake",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Junior Achievement (JA) Canada Awards",
        provider="Junior Achievement Canada",
        description="JA Canada recognizes high school students who participate in JA programs and demonstrate entrepreneurial thinking, financial literacy, and leadership. Award recipients receive scholarships from JA's corporate partners.",
        eligibility_criteria=[
            "Currently enrolled in a Canadian high school",
            "Participant in a Junior Achievement program",
            "Demonstrated entrepreneurship, leadership, or innovation",
        ],
        url="https://jacanada.org",
        source_domain="jacanada.org",
        levels=["high_school"],
        categories=["all"],
        amount="$1,000 – $10,000 (varies by award sponsor)",
        deadline_display="Check with your school's JA program coordinator",
        is_ra_ta=False,
    ),

    # ─── UNDERGRADUATE (entrance + current undergrad) ─────────────────────────

    ScholarshipRecord(
        name="Loran Award",
        provider="Loran Scholars Foundation",
        description="One of Canada's most prestigious entrance scholarships for students entering undergraduate studies. Awarded to students who demonstrate strength of character, service to community, and promise of leadership.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering first year of undergraduate study at a Loran partner university",
            "Strong community involvement and leadership record",
            "Minimum 85% average (varies by school)",
        ],
        url="https://loranscholar.ca/becoming-a-scholar/",
        source_domain="loranscholar.ca",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$100,000 over 4 years + mentorship",
        deadline_display="Early November (apply in Grade 12)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Schulich Leader Scholarships",
        provider="Schulich Foundation",
        description="Canada's most valuable STEM entrance scholarship, awarded to entrepreneurial-minded students entering a STEM undergraduate program at one of 20 Canadian universities.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering first year of an eligible STEM undergraduate program",
            "Nominated by your high school — one nominee per school",
            "Demonstrated entrepreneurial spirit and leadership",
        ],
        url="https://schulichleaders.com",
        source_domain="schulichleaders.com",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$100,000 (STEM) or $80,000 (other)",
        deadline_display="Nominated by your high school in Grade 12 — ask your school counsellor",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="TD Scholarship for Community Leadership",
        provider="TD Bank Group",
        description="Entrance scholarship for students entering post-secondary education who have made a significant difference in their communities through volunteer and leadership activities.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Entering post-secondary education (university, college, or trades)",
            "Demonstrated outstanding community leadership",
            "Financial need is considered",
        ],
        url="https://www.td.com/ca/en/about-td/community/scholarships/",
        source_domain="td.com",
        levels=["undergraduate", "diploma"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $70,000 over 4 years",
        deadline_display="February (apply in Grade 12)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Terry Fox Humanitarian Award",
        provider="Terry Fox Humanitarian Award Program",
        description="Entrance scholarship for students entering Canadian post-secondary education who exemplify Terry Fox's humanitarian spirit through outstanding volunteer and humanitarian work.",
        eligibility_criteria=[
            "Canadian citizen or landed immigrant",
            "Entering or enrolled in a Canadian post-secondary institution",
            "Demonstrated humanitarian and volunteer work",
            "Well-rounded with athletic involvement preferred",
        ],
        url="https://terryfox.org/award/",
        source_domain="terryfox.org",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $28,000/year",
        deadline_display="February 1 (apply in Grade 12)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Horatio Alger Canadian Scholarships",
        provider="Horatio Alger Association of Canada",
        description="Entrance scholarship for students in Grade 12 who have demonstrated integrity and perseverance in overcoming personal adversity and aspire to pursue post-secondary education.",
        eligibility_criteria=[
            "Canadian citizen",
            "Enrolled in Grade 12 (applying for post-secondary entry)",
            "Demonstrated financial need",
            "Have faced and overcome adversity",
            "Minimum 65% average",
        ],
        url="https://www.horatioalger.ca/en/scholarships/",
        source_domain="horatioalger.ca",
        levels=["undergraduate"],
        categories=["citizen"],
        amount="Up to $7,500",
        deadline_display="October 25 (apply in Grade 12)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="RBC Future Launch Scholarship",
        provider="RBC (Royal Bank of Canada)",
        description="Entrance and in-study scholarship supporting young Canadians as they transition into post-secondary education, with a focus on those facing barriers.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Age 15–29",
            "Enrolled in or planning to attend post-secondary education",
            "Demonstrated financial need or barrier to education",
        ],
        url="https://www.rbc.com/community-social-impact/rbc-future-launch/scholarships.html",
        source_domain="rbc.com",
        levels=["undergraduate", "diploma"],
        categories=["citizen", "permanent_resident"],
        amount="Varies by program",
        deadline_display="Check RBC website for current programs",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Indspire Building Brighter Futures Bursaries & Scholarships",
        provider="Indspire",
        description="Canada's largest Indigenous-led registered charity investing in Indigenous education. Scholarships for First Nations, Métis, and Inuit students at all post-secondary levels.",
        eligibility_criteria=[
            "First Nations, Métis, or Inuit student",
            "Canadian citizen or permanent resident",
            "Enrolled in or applying to a Canadian post-secondary institution",
            "Demonstrated financial need",
        ],
        url="https://indspire.ca/for-students/bursaries-scholarships/",
        source_domain="indspire.ca",
        levels=["diploma", "undergraduate", "masters"],
        categories=["citizen", "permanent_resident"],
        amount="$3,000 – $20,000+",
        deadline_display="March 1 and September 1 (two intakes per year)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Harry Jerome Scholarships",
        provider="Black Business and Professional Association (BBPA)",
        description="Awarded to Black-Canadian students at any post-secondary level who demonstrate academic achievement, community service, and leadership potential.",
        eligibility_criteria=[
            "Self-identified Black-Canadian student",
            "Canadian citizen or permanent resident",
            "Enrolled in a Canadian post-secondary institution",
            "Demonstrated community involvement",
        ],
        url="https://www.bbpa.org/harry-jerome-scholarships/",
        source_domain="bbpa.org",
        levels=["undergraduate", "masters"],
        categories=["citizen", "permanent_resident"],
        amount="$2,500 – $5,000",
        deadline_display="May 31",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Canada Post Community Foundation Scholarships",
        provider="Canada Post Community Foundation",
        description="Supports young Canadians entering or enrolled in post-secondary education, awarded based on academic excellence, community involvement, and financial need.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Age 24 or younger",
            "Enrolled in or planning to enroll in post-secondary education",
            "Demonstrated financial need and community involvement",
        ],
        url="https://www.canadapostcommunityfoundation.ca/scholarships/",
        source_domain="canadapostcommunityfoundation.ca",
        levels=["diploma", "undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 – $4,000",
        deadline_display="February (check website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="NSERC Undergraduate Student Research Awards (USRA)",
        provider="Natural Sciences and Engineering Research Council (NSERC)",
        description="Provides undergraduate students with research experience in a university setting under the supervision of a faculty member. Encourages students to consider graduate studies.",
        eligibility_criteria=[
            "Must be a Canadian citizen or permanent resident",
            "Registered full-time undergraduate student",
            "Minimum 70% average in last completed academic year",
            "Not yet graduated from the undergraduate program",
        ],
        url="https://www.nserc-crsng.gc.ca/Students-Etudiants/UG-PC/USRA-BRPC_eng.asp",
        source_domain="nserc-crsng.gc.ca",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$6,000 minimum for 16 weeks",
        deadline_display="Varies by university (typically February–March)",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="Mitacs Globalink Research Internship",
        provider="Mitacs",
        description="A competitive initiative for international undergraduates to conduct 12-week research internships at Canadian universities under the supervision of Canadian faculty members.",
        eligibility_criteria=[
            "International undergraduate student (not a Canadian citizen or PR)",
            "Completed at least 2 years of undergraduate study",
            "Strong academic record",
            "From one of Mitacs's partner countries",
        ],
        url="https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
        source_domain="mitacs.ca",
        levels=["undergraduate"],
        categories=["international"],
        amount="$6,000 CAD stipend for 12 weeks",
        deadline_display="September (check Mitacs website)",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="University of Toronto Excellence Award (UTEA)",
        provider="University of Toronto",
        description="Entrance scholarship automatically considered for all students admitted to an undergraduate program at U of T. No separate application required.",
        eligibility_criteria=[
            "Admitted to an undergraduate program at U of T",
            "Open to Canadian citizens, permanent residents, and international students",
            "Based on academic achievement at time of application",
        ],
        url="https://future.utoronto.ca/finances/awards/",
        source_domain="utoronto.ca",
        levels=["undergraduate"],
        categories=["all"],
        amount="$2,500 – $25,000",
        deadline_display="Automatic upon admission — no separate application",
        university="University of Toronto",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="UBC International Student Entrance Scholarships",
        provider="University of British Columbia",
        description="Merit-based entrance scholarships for international students admitted to undergraduate programs at UBC. Automatically considered at time of admission.",
        eligibility_criteria=[
            "International student (non-Canadian citizen or PR)",
            "Admitted to a full-time undergraduate program at UBC",
            "Exceptional academic achievement",
        ],
        url="https://students.ubc.ca/enrolment/finances/award-search/",
        source_domain="ubc.ca",
        levels=["undergraduate"],
        categories=["international"],
        amount="$2,000 – $40,000",
        deadline_display="Automatic upon admission",
        university="University of British Columbia",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="McGill University Entrance Scholarships",
        provider="McGill University",
        description="Merit-based entrance scholarships automatically considered for all students admitted to McGill undergraduate programs. No separate application required.",
        eligibility_criteria=[
            "Admitted to an undergraduate program at McGill",
            "Open to Canadian and international students",
            "Based on academic achievement",
        ],
        url="https://www.mcgill.ca/studentaid/scholarships-bursaries/undergraduate/entrance",
        source_domain="mcgill.ca",
        levels=["undergraduate"],
        categories=["all"],
        amount="$3,000 – $12,000",
        deadline_display="Automatic upon admission",
        university="McGill University",
        province="Quebec",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="3M National Student Fellowship",
        provider="3M Canada",
        description="Recognizes exceptional undergraduate students from across Canada who demonstrate academic excellence, community service, and leadership.",
        eligibility_criteria=[
            "Full-time undergraduate student at a Canadian university",
            "Canadian citizen or permanent resident",
            "Demonstrated academic excellence (minimum A average)",
            "Leadership and community involvement",
        ],
        url="https://www.3mcanada.ca",
        source_domain="3mcanada.ca",
        levels=["undergraduate"],
        categories=["citizen", "permanent_resident"],
        amount="$5,000",
        deadline_display="March (check 3M Canada website)",
        is_ra_ta=False,
    ),

    # ─── DIPLOMA ────────────────────────────────────────────────────────────

    ScholarshipRecord(
        name="Apprenticeship Incentive Grant (AIG)",
        provider="Government of Canada — Employment and Social Development",
        description="A taxable cash grant for registered apprentices who have completed their first or second year of a Red Seal trade apprenticeship program.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or protected person",
            "Registered apprentice in a Red Seal trade",
            "Completed first or second year of apprenticeship",
        ],
        url="https://www.canada.ca/en/employment-social-development/services/apprentices/grants.html",
        source_domain="canada.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 per year (first and second year)",
        deadline_display="Within 12 months of completing your level",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Apprenticeship Completion Grant (ACG)",
        provider="Government of Canada — Employment and Social Development",
        description="A taxable cash grant for apprentices who complete their apprenticeship and receive their journeyperson certification in a designated Red Seal trade.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or protected person",
            "Completed apprenticeship in a Red Seal trade",
            "Received journeyperson certification",
        ],
        url="https://www.canada.ca/en/employment-social-development/services/apprentices/grants.html",
        source_domain="canada.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$2,000 (one-time upon certification)",
        deadline_display="Within 12 months of receiving certification",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Women in Skilled Trades Scholarship — Ontario",
        provider="Ontario Ministry of Labour, Immigration, Training and Skills Development",
        description="Supports women enrolled in apprenticeship programs or pre-apprenticeship training in skilled trades in Ontario.",
        eligibility_criteria=[
            "Self-identified woman",
            "Ontario resident",
            "Registered in an Ontario apprenticeship or pre-apprenticeship program",
        ],
        url="https://www.ontario.ca/page/scholarships-women-skilled-trades-and-technology",
        source_domain="ontario.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$5,000",
        deadline_display="Check Ontario.ca for current intake",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="BC Trades & Technology Scholarship",
        provider="Government of British Columbia — StudentAid BC",
        description="Supports students in trades and technology programs at BC public post-secondary institutions who demonstrate financial need.",
        eligibility_criteria=[
            "BC resident",
            "Enrolled in an eligible trades or technology program at a BC public institution",
            "Canadian citizen, permanent resident, or protected person",
            "Demonstrated financial need",
        ],
        url="https://studentaidbc.ca/explore/scholarships-and-grants",
        source_domain="studentaidbc.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="Up to $4,000",
        deadline_display="Check StudentAid BC website",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Alberta Apprenticeship & Industry Training Scholarships",
        provider="Government of Alberta — Apprenticeship and Industry Training",
        description="Scholarships for Alberta apprentices who demonstrate academic excellence and commitment to their trade during technical training.",
        eligibility_criteria=[
            "Alberta resident",
            "Registered apprentice in Alberta",
            "Completed at least one period of technical training",
            "Demonstrated academic achievement in training",
        ],
        url="https://www.alberta.ca/apprenticeship-scholarships",
        source_domain="alberta.ca",
        levels=["diploma"],
        categories=["citizen", "permanent_resident"],
        amount="$1,000 – $5,000",
        deadline_display="June 30 (check Alberta.ca)",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="George Brown College Awards & Bursaries",
        provider="George Brown College",
        description="Various awards and bursaries for George Brown College students based on academic merit, financial need, and program of study.",
        eligibility_criteria=[
            "Enrolled at George Brown College",
            "Criteria vary by award — merit, need, or program-based",
            "Some awards open to international students",
        ],
        url="https://www.georgebrown.ca/current-students/services/financial-aid/awards-bursaries",
        source_domain="georgebrown.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $5,000+",
        deadline_display="September and January (check George Brown portal)",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="BCIT Excellence Awards",
        provider="British Columbia Institute of Technology (BCIT)",
        description="Scholarships and awards for BCIT students across trades, technology, business, and health sciences programs.",
        eligibility_criteria=[
            "Enrolled at BCIT",
            "Criteria vary — some merit-based, some need-based",
            "Some awards open to international students",
        ],
        url="https://www.bcit.ca/financial-aid/awards/",
        source_domain="bcit.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $5,000",
        deadline_display="March 15 and September 30 (check BCIT portal)",
        province="British Columbia",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Seneca Polytechnic Awards",
        provider="Seneca Polytechnic",
        description="Wide range of scholarships for students in diploma, certificate, and degree programs at Seneca, including entrance and in-course awards.",
        eligibility_criteria=[
            "Enrolled at Seneca Polytechnic",
            "Academic achievement or demonstrated financial need",
            "Some awards open to international students",
        ],
        url="https://www.senecapolytechnic.ca/financial-aid/awards-scholarships.html",
        source_domain="senecapolytechnic.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $4,000",
        deadline_display="Check Seneca financial aid portal",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Conestoga College Scholarships & Awards",
        provider="Conestoga College",
        description="Merit-based and need-based scholarships for students in diploma and certificate programs at Conestoga College in Ontario.",
        eligibility_criteria=[
            "Enrolled at Conestoga College",
            "Minimum GPA requirement varies by award",
            "Some awards open to international students",
        ],
        url="https://www.conestogac.on.ca/financial-aid/awards",
        source_domain="conestogac.on.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $2,500",
        deadline_display="Check Conestoga financial aid portal",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Bow Valley College Scholarship Program",
        provider="Bow Valley College",
        description="Scholarships and bursaries for students enrolled at Bow Valley College in Calgary, including entrance awards and in-course awards.",
        eligibility_criteria=[
            "Enrolled at Bow Valley College",
            "Varies by award — merit or need-based",
            "Some awards open to international students",
        ],
        url="https://bowvalleycollege.ca/student-resources/financial-support/scholarships-and-bursaries",
        source_domain="bowvalleycollege.ca",
        levels=["diploma"],
        categories=["all"],
        amount="$500 – $3,000",
        deadline_display="Varies by award (check BVC portal)",
        province="Alberta",
        is_ra_ta=False,
    ),

    # ─── MASTERS / PHD ───────────────────────────────────────────────────────

    ScholarshipRecord(
        name="Vanier Canada Graduate Scholarships",
        provider="Government of Canada",
        description="Attracts and retains world-class doctoral students by supporting those who demonstrate leadership skills and a high standard of scholarly achievement in graduate studies.",
        eligibility_criteria=[
            "Doctoral student (PhD or combined MA/PhD)",
            "Nominated by a Canadian university",
            "Canadian citizens, permanent residents, and international students are eligible",
            "Demonstrated leadership and high scholarly achievement",
        ],
        url="https://vanier.gc.ca/en/home-accueil.html",
        source_domain="vanier.gc.ca",
        levels=["masters"],
        categories=["all"],
        amount="$50,000/year for 3 years",
        deadline_display="Early November (check Vanier website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Canada Graduate Scholarships — Master's (CGS-M)",
        provider="NSERC / SSHRC / CIHR",
        description="Provides financial support to high-calibre scholars engaged in master's-level studies in the natural sciences, engineering, social sciences, humanities, or health.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Enrolled in a master's or combined bachelor's/master's program",
            "Minimum A- average in last two years of full-time study",
        ],
        url="https://www.nserc-crsng.gc.ca/Students-Etudiants/PG-CS/CGSM-BESCM_eng.asp",
        source_domain="nserc-crsng.gc.ca",
        levels=["masters"],
        categories=["citizen", "permanent_resident"],
        amount="$17,500 for 1 year",
        deadline_display="December (check NSERC website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Canada Graduate Scholarships — Doctoral (CGS-D / PGS-D)",
        provider="NSERC / SSHRC / CIHR",
        description="Supports Canadian citizens and permanent residents pursuing doctoral programs in natural sciences, engineering, social sciences, humanities, or health.",
        eligibility_criteria=[
            "Canadian citizen or permanent resident",
            "Registered or planning to register in a doctoral program",
            "Minimum A- average",
            "Demonstrated research potential",
        ],
        url="https://www.nserc-crsng.gc.ca/Students-Etudiants/PG-CS/CGSD-BESCD_eng.asp",
        source_domain="nserc-crsng.gc.ca",
        levels=["masters"],
        categories=["citizen", "permanent_resident"],
        amount="CGS-D: $35,000/year | PGS-D: $21,000/year",
        deadline_display="October (check NSERC website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Pierre Elliott Trudeau Foundation Doctoral Scholarships",
        provider="Pierre Elliott Trudeau Foundation",
        description="Supports outstanding PhD candidates whose research focuses on human rights and dignity, responsible citizenship, Canada and the world, or people and their natural environment.",
        eligibility_criteria=[
            "Canadian citizen, permanent resident, or international student at a Canadian university",
            "Enrolled in a full-time PhD program at a Canadian university",
            "Research aligned with one of the four Foundation themes",
            "Demonstrated leadership and public engagement",
        ],
        url="https://www.trudeaufoundation.ca/programs/trudeau-scholarships",
        source_domain="trudeaufoundation.ca",
        levels=["masters"],
        categories=["all"],
        amount="$40,000/year for up to 3 years + travel allowance",
        deadline_display="Early December (check Trudeau Foundation website)",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Ontario Graduate Scholarship (OGS)",
        provider="Government of Ontario",
        description="Promotes excellence in graduate study at publicly-assisted Ontario universities. Merit-based and available across all disciplines to domestic and international students.",
        eligibility_criteria=[
            "Enrolled in a graduate program (master's or PhD) at an Ontario university",
            "Open to Canadian citizens, permanent residents, and international students",
            "Strong academic record (A average or better)",
        ],
        url="https://osap.gov.on.ca/OSAPPortal/en/A-ZListofAid/PRDR019245.html",
        source_domain="ontario.ca",
        levels=["masters"],
        categories=["all"],
        amount="$15,000/year",
        deadline_display="Varies by university — typically January to March",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Ontario Trillium Scholarship (OTS)",
        provider="Government of Ontario",
        description="Attracts top international PhD students to study at Ontario universities. One of the most valuable scholarships for international doctoral students in Canada.",
        eligibility_criteria=[
            "International student (not Canadian citizen or PR)",
            "Applying to or enrolled in a full-time PhD program at an Ontario university",
            "Exceptional academic achievement",
            "Nominated by the university — contact your graduate department",
        ],
        url="https://www.ontario.ca/page/ontario-trillium-scholarship",
        source_domain="ontario.ca",
        levels=["masters"],
        categories=["international"],
        amount="$40,000/year for up to 4 years",
        deadline_display="Nominated by university — check with your graduate department",
        province="Ontario",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Alberta Graduate Excellence Scholarship (AGES)",
        provider="Government of Alberta",
        description="Recognizes and retains exceptional graduate students studying at Alberta post-secondary institutions. Open to domestic and international students.",
        eligibility_criteria=[
            "Enrolled in a graduate program at an Alberta university",
            "Canadian citizen, permanent resident, or international student",
            "Strong academic record",
            "Nominated by the university",
        ],
        url="https://www.alberta.ca/alberta-graduate-excellence-scholarship",
        source_domain="alberta.ca",
        levels=["masters"],
        categories=["all"],
        amount="$11,000/year",
        deadline_display="Nominated by university — check with your graduate department",
        province="Alberta",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Killam Doctoral Scholarships",
        provider="Canada Council for the Arts — Killam Program",
        description="Awarded to outstanding PhD students at UBC, Dalhousie, University of Alberta, University of Calgary, and Western University.",
        eligibility_criteria=[
            "Enrolled in a PhD program at UBC, Dalhousie, U of Alberta, U of Calgary, or Western",
            "Nominated by the university department",
            "Exceptional academic achievement and research potential",
        ],
        url="https://killam.ca/doctoral-scholarships/",
        source_domain="killam.ca",
        levels=["masters"],
        categories=["all"],
        amount="$30,000/year for 2 years",
        deadline_display="Nominated by university — check with your graduate department",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="McCall MacBain Scholarships at McGill",
        provider="McCall MacBain Foundation — McGill University",
        description="Full-funding scholarships for exceptional students pursuing master's or professional programs at McGill. Selected for leadership potential and commitment to positive impact.",
        eligibility_criteria=[
            "Applying to a master's or professional program at McGill",
            "Open to Canadian citizens, permanent residents, and international students",
            "Demonstrated leadership, academic excellence, and community impact",
        ],
        url="https://www.mccallmacbainscholars.org",
        source_domain="mccallmacbainscholars.org",
        levels=["masters"],
        categories=["all"],
        amount="Full tuition + living stipend + mentorship",
        deadline_display="November (check McCall MacBain website)",
        university="McGill University",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Mitacs Accelerate",
        provider="Mitacs",
        description="Connects graduate students and postdocs with industry or non-profit partners for research internships. Rolling applications accepted year-round.",
        eligibility_criteria=[
            "Graduate student (master's or PhD) or postdoctoral fellow",
            "Enrolled at a Canadian university",
            "Canadian citizen, permanent resident, or international student",
            "Research project in partnership with an industry or non-profit partner",
        ],
        url="https://www.mitacs.ca/en/programs/accelerate",
        source_domain="mitacs.ca",
        levels=["masters"],
        categories=["all"],
        amount="$15,000 per 3-month unit (student receives $10,000)",
        deadline_display="Rolling applications — apply anytime",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="FRQSC Doctoral Scholarships (Quebec)",
        provider="Fonds de recherche du Québec — Société et culture",
        description="Supports doctoral students in social sciences and humanities conducting research at Quebec universities.",
        eligibility_criteria=[
            "Enrolled in a doctoral program at a Quebec university",
            "Canadian citizen or permanent resident (or authorized to study in Quebec)",
            "Research in social sciences, humanities, or related fields",
        ],
        url="https://frq.gouv.qc.ca/en/program/doctoral-training-scholarships/",
        source_domain="frq.gouv.qc.ca",
        levels=["masters"],
        categories=["citizen", "permanent_resident"],
        amount="$20,000/year for up to 4 years",
        deadline_display="October (check FRQSC website)",
        province="Quebec",
        is_ra_ta=False,
    ),

    ScholarshipRecord(
        name="Banting Postdoctoral Fellowships",
        provider="Government of Canada (NSERC / SSHRC / CIHR)",
        description="Provides funding to top-tier postdoctoral researchers nationally and internationally who will contribute to Canada's economic, social, and research growth.",
        eligibility_criteria=[
            "Completed PhD within the last 3 years",
            "Canadian citizen, permanent resident, or international researcher",
            "Nominated by a Canadian university",
            "Exceptional research track record",
        ],
        url="https://banting.fellowships-bourses.gc.ca",
        source_domain="banting.fellowships-bourses.gc.ca",
        levels=["masters"],
        categories=["all"],
        amount="$70,000/year for 2 years",
        deadline_display="September (check Banting website)",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="UBC Graduate Support Initiative",
        provider="University of British Columbia",
        description="UBC guarantees a minimum funding package for PhD students across all faculties, combining fellowship, TA, and RA funding.",
        eligibility_criteria=[
            "Admitted to a full-time PhD program at UBC",
            "Open to Canadian citizens, permanent residents, and international students",
            "Funding guaranteed for eligible PhD students — no separate application",
        ],
        url="https://www.grad.ubc.ca/scholarships-awards-funding",
        source_domain="grad.ubc.ca",
        levels=["masters"],
        categories=["all"],
        amount="Typically $22,000+/year (fellowship + TA/RA combined)",
        deadline_display="Automatic upon PhD admission — no separate application",
        university="University of British Columbia",
        province="British Columbia",
        is_ra_ta=True,
    ),

    ScholarshipRecord(
        name="University of Waterloo International Master's Award of Excellence",
        provider="University of Waterloo",
        description="Awarded to exceptional international students admitted to a master's program at the University of Waterloo.",
        eligibility_criteria=[
            "International student (non-Canadian citizen or PR)",
            "Admitted to a full-time master's program at Waterloo",
            "Minimum 80% average in last two years of study",
            "Nominated by department",
        ],
        url="https://uwaterloo.ca/graduate-studies-postdoctoral-affairs/awards/university-waterloo-international-masters-award-excellence",
        source_domain="uwaterloo.ca",
        levels=["masters"],
        categories=["international"],
        amount="$5,000",
        deadline_display="Contact your department for deadline",
        university="University of Waterloo",
        province="Ontario",
        is_ra_ta=False,
    ),
]


class SeedScraper(BaseScraper):
    name = "seed"
    source_domain = "fundmydegree.com"

    def scrape(self) -> list[ScholarshipRecord]:
        import logging
        logger = logging.getLogger(__name__)
        logger.info(f"Loading {len(SEED_SCHOLARSHIPS)} curated seed scholarships")
        return SEED_SCHOLARSHIPS
